[env:diy_luatos_e22_30s]
extends = esp32c3_base
board = esp32-c3-devkitm-1
upload_protocol = esptool
upload_speed = 921600
monitor_speed = 115200

build_flags =
  ${esp32_base.build_flags}
  -D PRIVATE_HW
  -D BOARD_FLASH_CS=14
  -D BOARD_FLASH_CLK=15
  -D BOARD_FLASH_MOSI=16
  -D BOARD_FLASH_MISO=17
  -I variants/esp32c3/diy_luatos_e22_30s

board_build.flash_mode = dio
board_build.f_flash = 40000000L
board_build.flash_size = 4MB
board_build.filesystem = littlefs
board_build.partitions = partition-table_luatos.csv


[env:diy_luatos_e22_30s_m1nl]
extends = env:diy_luatos_e22_30s
platform_packages =
    platformio/framework-arduinoespressif32 @ https://github.com/m1nl/arduino-esp32/archive/refs/tags/2.0.17+5ae9873e.tar.gz ; disable WiFi IRAM optimizations in ESP-IDF