
[env:heltec-wireless-paper-inkhud-ru]
extends = esp32s3_base, inkhud
board = heltec_wifi_lora_32_V3
board_build.partitions = default_8MB.csv
build_src_filter =
  ${esp32s3_base.build_src_filter} 
  ${inkhud.build_src_filter}
build_flags =
  ${esp32s3_base.build_flags}
  ${inkhud.build_flags}
  -I variants/esp32s3/heltec_wireless_paper_ru
  -D HELTEC_WIRELESS_PAPER
lib_deps =
  ${inkhud.lib_deps} ; InkHUD libs first, so we get GFXRoot instead of AdafruitGFX
  ${esp32s3_base.lib_deps}
upload_speed = 921600
